"""add rating in product

Revision ID: 272bcd5728b1
Revises: 477ffc083c40
Create Date: 2026-03-01 15:17:00.547858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272bcd5728b1'
down_revision: Union[str, Sequence[str], None] = '477ffc083c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
